# Generated by Django 2.2.5 on 2019-09-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='states',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
